import { JsonLd, Layout, PageMeta } from "@/components/Storefront";
import { trpc } from "@/lib/trpc";
import { useLanguage } from "@/contexts/LanguageContext";
import { CheckCircle2, KeyRound, Loader2, LogIn, LogOut, MapPin, ShieldCheck } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";

function AccountShell({ children, title, description }: { children: React.ReactNode; title: string; description: string }) {
  return <Layout><PageMeta title={title} description={description} /><JsonLd /><main className="account-page"><section className="page-frame account-frame">{children}</section></main></Layout>;
}

export default function CustomerAccount() {
  const { language } = useLanguage();
  const [location, setLocation] = useLocation();
  const account = trpc.customer.me.useQuery();
  const login = trpc.customer.login.useMutation({
    onSuccess: async () => { await account.refetch(); toast.success(language === "en" ? "You signed in successfully." : "Влязохте успешно в профила си."); },
    onError: (error) => toast.error(error.message || (language === "en" ? "Sign-in was not successful. Check your details." : "Входът не е успешен. Проверете данните си.")),
  });
  const logout = trpc.customer.logout.useMutation({ onSuccess: async () => { await account.refetch(); toast.success(language === "en" ? "You signed out of your account." : "Излязохте от профила си."); setLocation("/"); } });
  const [error, setError] = useState("");

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const email = String(form.get("email") ?? "").trim();
    const password = String(form.get("password") ?? "");
    if (!email || !password) { setError(language === "en" ? "Enter an email and password." : "Попълнете имейл и парола."); return; }
    setError("");
    login.mutate({ email, password });
  }

  if (account.isLoading) return <AccountShell title={language === "en" ? "Account" : "Профил"} description={language === "en" ? "Sign in to a Joan customer account." : "Вход в клиентски профил на Жоан."}><div className="account-loading"><Loader2 className="animate-spin" size={24} /> {language === "en" ? "Loading account…" : "Зареждане на профил…"}</div></AccountShell>;
  if (account.data) {
    const profile = account.data;
    return <AccountShell title={language === "en" ? "My account" : "Моят профил"} description={language === "en" ? "View your customer account, saved addresses and available order history." : "Преглед на клиентския профил, запазените адреси и наличната историческа информация."}>
      <div className="account-hero"><p className="eyebrow">{language === "en" ? "CUSTOMER ACCOUNT" : "КЛИЕНТСКИ ПРОФИЛ"}</p><h1>{language === "en" ? "Hello" : "Здравейте"}, {profile.firstName}.</h1><p>{language === "en" ? "Your account and saved addresses are ready to use." : "Вашият профил и запазените адреси са готови за използване."}</p></div>
      <section className="account-card account-profile-card"><div><span className="account-icon"><ShieldCheck size={22} /></span><div><p className="eyebrow">{language === "en" ? "PROFILE DETAILS" : "ДАННИ ЗА ПРОФИЛА"}</p><h2>{profile.firstName} {profile.lastName}</h2><a href={`mailto:${profile.email}`}>{profile.email}</a>{profile.phone && <p>{profile.phone}</p>}</div></div><button type="button" className="button-outline" disabled={logout.isPending} onClick={() => logout.mutate()}><LogOut size={17} /> {language === "en" ? "Sign out" : "Изход"}</button></section>
      <section className="account-address-section"><div><p className="eyebrow">{language === "en" ? "SAVED ADDRESSES" : "ЗАПАЗЕНИ АДРЕСИ"}</p><h2>{language === "en" ? "Delivery addresses" : "Адреси за доставка"}</h2></div>{profile.addresses.length ? <div className="account-address-grid">{profile.addresses.map((address) => <article key={address.id} className="account-address-card"><MapPin size={20} /><div><b>{address.firstName} {address.lastName}</b>{address.company && <span>{address.company}</span>}<span>{address.addressLine1}</span>{address.addressLine2 && <span>{address.addressLine2}</span>}<span>{address.postcode ? `${address.postcode} ` : ""}{address.city}</span>{address.zone && <span>{address.zone}</span>}{address.country && <span>{address.country}</span>}{address.isDefault && <small>{language === "en" ? "Default address" : "Основен адрес"}</small>}</div></article>)}</div> : <p className="account-empty">{language === "en" ? "There is no saved address for this account yet." : "Към профила все още няма запазен адрес."}</p>}</section>
      <section className="account-history-section"><div><p className="eyebrow">{language === "en" ? "ORDER HISTORY" : "ИСТОРИЧЕСКИ ПОРЪЧКИ"}</p><h2>{language === "en" ? "Previous orders" : "Предишни заявки"}</h2><p>{language === "en" ? "Only orders from the former website that are linked to this customer account are shown." : "Показват се единствено поръчки от стария сайт, които са свързани с този клиентски профил."}</p></div>{profile.historicalOrders.length ? <div className="account-history-list">{profile.historicalOrders.map((order) => <details key={order.legacyOrderId} className="account-history-order"><summary><span><b>{language === "en" ? "Order" : "Поръчка"} №{order.legacyOrderId}</b><small>{new Date(order.orderedAt).toLocaleDateString(language === "en" ? "en-GB" : "bg-BG", { dateStyle: "medium" })}</small></span><span><em>{order.orderStatus}</em><strong>{Number(order.totalInOrderCurrency ?? order.total).toFixed(2)} {order.currencyCode}</strong></span></summary><div>{order.lines.map((line, index) => <p key={`${line.productName}-${index}`}><span>{line.productName}{line.productModel ? ` · ${line.productModel}` : ""} × {line.quantity}</span><b>{Number(line.lineTotal).toFixed(2)} {order.currencyCode}</b></p>)}</div></details>)}</div> : <p className="account-empty">{language === "en" ? "There are no historical orders linked to this account." : "Няма исторически поръчки, свързани с този профил."}</p>}</section>
    </AccountShell>;
  }

  return <AccountShell title={language === "en" ? "Sign in" : "Вход"} description={language === "en" ? "Sign in to a Joan customer account." : "Вход за клиентски профил на Жоан."}><div className="account-auth-grid"><section className="account-hero"><p className="eyebrow">{language === "en" ? "CUSTOMER ACCOUNT" : "КЛИЕНТСКИ ПРОФИЛ"}</p><h1>{language === "en" ? "Sign in to your account." : "Влезте в своя профил."}</h1><p>{language === "en" ? "View your saved addresses and use your account for future orders." : "Прегледайте запазените си адреси и използвайте профила си при бъдещи поръчки."}</p><div className="account-note"><KeyRound size={20} /><span><b>{language === "en" ? "First sign-in after migration?" : "Първо влизане след прехвърлянето?"}</b> {language === "en" ? "You will receive a secure link to set a new password for your existing account." : "Ще получите защитен линк, с който да зададете нова парола за вече съществуващия си профил."}</span></div></section><form className="account-card account-login-form" onSubmit={submit} noValidate><div><p className="eyebrow">{language === "en" ? "SIGN IN" : "ВХОД"}</p><h2>{language === "en" ? "Welcome back" : "Добре дошли отново"}</h2></div><label>{language === "en" ? "Email" : "Имейл"}<input name="email" type="email" autoComplete="email" placeholder="email@example.com" disabled={login.isPending} /></label><label>{language === "en" ? "Password" : "Парола"}<input name="password" type="password" autoComplete="current-password" placeholder={language === "en" ? "Your password" : "Вашата парола"} disabled={login.isPending} /></label>{error && <p className="account-error" role="alert">{error}</p>}<button type="submit" className="button-solid" disabled={login.isPending} aria-busy={login.isPending}>{login.isPending ? <><Loader2 className="animate-spin" size={18} /> {language === "en" ? "Checking…" : "Проверка…"}</> : <><LogIn size={18} /> {language === "en" ? "Sign in" : "Вход в профила"}</>}</button><p className="account-help">{language === "en" ? "If your account was migrated from the former website, use the first-activation link sent to your email. Need help?" : "Ако профилът ви е прехвърлен от стария сайт, използвайте линка за първо активиране, изпратен на имейла ви. Нужда от помощ?"} <Link href="/contact">{language === "en" ? "Contact us" : "Свържете се с нас"}</Link>.</p></form></div></AccountShell>;
}

export function CustomerActivation() {
  const { language } = useLanguage();
  const [, setLocation] = useLocation();
  const initialToken = useMemo(() => new URLSearchParams(window.location.search).get("token") ?? "", []);
  const [token, setToken] = useState(initialToken);
  const [message, setMessage] = useState("");
  const activation = trpc.customer.activate.useMutation({ onSuccess: () => { setMessage(language === "en" ? "Your password was set successfully. Signing you in…" : "Паролата е зададена успешно. Влизате в профила си…"); window.setTimeout(() => setLocation("/account"), 850); }, onError: (error) => setMessage(error.message || (language === "en" ? "The activation link is not valid." : "Линкът за активиране не е валиден.")) });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const password = String(form.get("password") ?? ""); const confirmation = String(form.get("confirmation") ?? ""); if (password !== confirmation) { setMessage(language === "en" ? "The two passwords do not match." : "Двете пароли не съвпадат."); return; } setMessage(""); activation.mutate({ token: token.trim(), password }); }
  return <AccountShell title={language === "en" ? "Activate your account" : "Активирайте профила си"} description={language === "en" ? "Set a new secure password for your customer account." : "Задайте нова защитена парола за своя клиентски профил."}><div className="account-activation"><section className="account-hero"><p className="eyebrow">{language === "en" ? "ACCOUNT ACTIVATION" : "АКТИВИРАНЕ НА ПРОФИЛ"}</p><h1>{language === "en" ? "Set a new password." : "Задайте нова парола."}</h1><p>{language === "en" ? "This link can be used once. Previous password details are not used after successful activation." : "Този линк е еднократен. След успешно активиране старите данни за парола не се използват."}</p></section><form className="account-card account-login-form" onSubmit={submit}><label>{language === "en" ? "Code from the link" : "Код от линка"}<input value={token} onChange={(event) => setToken(event.target.value)} required minLength={32} maxLength={160} autoComplete="off" disabled={activation.isPending} /></label><label>{language === "en" ? "New password" : "Нова парола"}<input name="password" type="password" required minLength={12} autoComplete="new-password" placeholder={language === "en" ? "At least 12 characters" : "Поне 12 символа"} disabled={activation.isPending} /></label><label>{language === "en" ? "Repeat password" : "Повторете паролата"}<input name="confirmation" type="password" required minLength={12} autoComplete="new-password" disabled={activation.isPending} /></label>{message && <p className={activation.isSuccess ? "account-success" : "account-error"} role="status">{activation.isSuccess && <CheckCircle2 size={18} />}{message}</p>}<button type="submit" className="button-solid" disabled={activation.isPending}>{activation.isPending ? <><Loader2 className="animate-spin" size={18} /> {language === "en" ? "Activating…" : "Активиране…"}</> : <><KeyRound size={18} /> {language === "en" ? "Save new password" : "Запази новата парола"}</>}</button></form></div></AccountShell>;
}
