/** FAQ support page with complete Bulgarian and English customer-facing copy. */
import { Layout, PageMeta } from "@/components/Storefront";
import { useLanguage } from "@/contexts/LanguageContext";
import { ArrowRight, ChevronDown, Mail, MessageCircleQuestion, Phone } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const faqItems = { bg: [["Как започвам запитване за връщане?", "Свържете се с екипа чрез страницата „Връщане“ или „Контакти“. Подгответе име, телефон, имейл, номер и дата на поръчката, продукта, кода и количеството."], ["Какво е входящ номер за връщане (RMA)?", "Това е референтен номер за заявката, който помага на екипа да проследи конкретното връщане. Той се потвърждава след преглед на данните за поръчката и продукта."], ["Колко време имам за отказ от поръчка?", "Публикуваните условия на ЖОАН посочват 14 дни от получаването на стоката при приложимост. Вижте условията за изключенията и пълните детайли."], ["Мога ли да изпратя продукта веднага?", "Първо се свържете с екипа, за да получите указания за конкретния случай и за начина на предаване или изпращане."], ["Какво да направя при дефект или грешно изпратен продукт?", "Опишете случая и се свържете с екипа възможно най-скоро. Подгответе данните за продукта и поръчката, за да получите точни следващи стъпки."], ["Как мога да проверя наличност или срок за доставка?", "Изпратете запитване през контактната форма или се обадете на екипа. Наличността и срокът се потвърждават индивидуално за конкретния продукт и адрес."]], en: [["How do I start a return enquiry?", "Contact the team through the Returns or Contact page. Prepare your name, phone, email, order number and date, product, code and quantity."], ["What is a return reference number (RMA)?", "It is a reference number for the enquiry that helps the team follow a specific return. It is confirmed after the order and product details are reviewed."], ["How long do I have to withdraw from an order?", "Joan’s published terms state 14 days from receiving the goods where applicable. See the terms for exclusions and full details."], ["Can I send the product immediately?", "Contact the team first to receive instructions for the individual case and handover or shipping method."], ["What should I do for a defect or incorrectly dispatched product?", "Describe the case and contact the team as soon as possible. Prepare the product and order details to receive accurate next steps."], ["How can I check availability or a delivery timeframe?", "Send an enquiry through the contact form or call the team. Availability and timeframe are confirmed individually for the specific product and address."]] } as const;

export default function FAQ() {
  const { language } = useLanguage(); const en = language === "en"; const [openIndex, setOpenIndex] = useState<number | null>(0);
  return <Layout><PageMeta title={en ? "Frequently asked questions" : "Често задавани въпроси"} description={en ? "Frequently asked questions about returns, availability, delivery and contacting Joan." : "Често задавани въпроси за връщане, наличности, доставка и контакт с ЖОАН."} /><main className="faq-page"><section className="faq-hero"><div className="page-frame"><p className="eyebrow">{en ? "Help centre" : "Помощен център"}</p><h1>{en ? "Frequently asked questions" : "Често задавани въпроси"}</h1><p>{en ? "Quick answers about returns, availability, delivery and next steps. For a specific order, the Joan team confirms the applicable terms." : "Бързи отговори за връщане, наличност, доставка и следващи стъпки. За конкретна поръчка екипът на ЖОАН потвърждава приложимите условия."}</p><div className="faq-hero-actions"><Link href="/returns" className="button-solid">{en ? "Product returns" : "Връщане на продукти"} <ArrowRight size={18} /></Link><Link href="/contact" className="button-outline-dark">{en ? "Send an enquiry" : "Изпратете запитване"} <ArrowRight size={18} /></Link></div></div></section><section className="page-frame faq-content" aria-labelledby="faq-list-title"><div className="faq-intro"><MessageCircleQuestion size={26} /><p className="eyebrow">{en ? "Answers" : "Отговори"}</p><h2 id="faq-list-title">{en ? "Information before you contact us." : "Информация преди да се свържете с нас."}</h2><p>{en ? "This page brings together the most common questions. It is informational and does not submit an automatic request or order." : "Страницата събира най-честите въпроси на едно място. Тя е информационна и не подава автоматично заявление или поръчка."}</p></div><div className="faq-list">{faqItems[language].map(([question, answer], index) => { const isOpen = openIndex === index; const answerId = `faq-answer-${index}`; return <article key={question} className={`faq-item${isOpen ? " is-open" : ""}`}><button type="button" className="faq-question" aria-expanded={isOpen} aria-controls={answerId} onClick={() => setOpenIndex(isOpen ? null : index)}><span><em>{String(index + 1).padStart(2, "0")}</em>{question}</span><ChevronDown size={19} aria-hidden="true" /><span className="sr-only">{isOpen ? (en ? "Collapse answer" : "Прибери отговора") : (en ? "Expand answer" : "Разгъни отговора")}</span></button><div id={answerId} className="faq-answer" aria-hidden={!isOpen}><div><p>{answer}</p></div></div></article>; })}</div></section><section className="page-frame faq-contact-strip"><div><p className="eyebrow">{en ? "Still have a question?" : "Все още имате въпрос?"}</p><h2>{en ? "The Joan team is here to help." : "Екипът на ЖОАН е насреща."}</h2></div><div><a href="tel:+359884742770"><Phone size={18} /> (0884) 742 770</a><a href="mailto:info@joan.bg"><Mail size={18} /> info@joan.bg</a></div></section></main></Layout>;
}
