/** DESIGN REMINDER — Red Workshop Modernism: factual return guidance with clear procedural hierarchy, never a decorative legal wall. */
import { Layout, PageMeta } from "@/components/Storefront";
import { store } from "@/lib/storeData";
import { ArrowRight, ArrowUpRight, BadgeAlert, ClipboardList, FileCheck2, Mail, MapPin, PackageCheck, Phone, RotateCcw, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const originalTermsUrl = "https://joan.bg/index.php?route=information/information/agree&information_id=5";

export default function Returns() {
  return <Layout><PageMeta title="Връщане на продукти" description="Информация за връщане на продукти, право на отказ и връзка с екипа на ЖОАН." /><main className="returns-page">
    <section className="returns-hero"><div className="page-frame returns-hero-grid"><div><p className="eyebrow">Клиентска информация</p><h1>Връщане на продукти, без излишни стъпки.</h1><p>Тук ще откриете каква информация да подготвите и как екипът на ЖОАН координира заявките за връщане. Всеки случай се преглежда спрямо приложимите условия и данните от поръчката.</p><div className="returns-hero-actions"><a href="#return-steps" className="button-solid">Вижте стъпките <ArrowRight size={18} /></a><Link href="/contact" className="button-outline-light">Свържете се с нас <ArrowRight size={18} /></Link></div></div><aside className="returns-deadline"><RotateCcw size={25} /><span>Право на отказ</span><strong>14 дни</strong><p>При приложимост, считано от получаването на стоката.</p></aside></div></section>

    <section id="return-steps" className="page-frame returns-process"><div className="returns-section-heading"><p className="eyebrow">Как започва заявката</p><h2>Три ясни стъпки</h2><p>Оригиналният сайт използва входящ номер за връщане (RMA). В този редизайн първата стъпка е директна връзка с екипа, който ще потвърди последващите действия.</p></div><div className="returns-step-grid"><article><span>01</span><ClipboardList size={23} /><h3>Подгответе данните</h3><p>Посочете име, телефон, имейл, номер и дата на поръчката, име на продукта, код и количество.</p></article><article><span>02</span><FileCheck2 size={23} /><h3>Опишете случая</h3><p>Уточнете причината за връщането: дефект, грешно изпратен продукт, сгрешена поръчка или друга причина.</p></article><article><span>03</span><PackageCheck size={23} /><h3>Изчакайте потвърждение</h3><p>Екипът ще прегледа заявката и ще даде указания за входящ номер, предаване или изпращане на продукта.</p></article></div></section>

    <section className="returns-conditions"><div className="page-frame returns-conditions-grid"><div className="returns-condition-copy"><p className="eyebrow">Условия при право на отказ</p><h2>Проверете дали случаят ви отговаря на публикуваните условия.</h2><p>Оригиналните условия на ЖОАН посочват 14-дневен срок за отказ при приложимост. Те съдържат и конкретни изисквания за състоянието на стоката, документите и сроковете за предаване обратно.</p><a href={originalTermsUrl} target="_blank" rel="noreferrer">Прочетете пълните условия на ЖОАН <ArrowUpRight size={17} /></a></div><div className="returns-condition-list"><div><ShieldCheck size={20} /><span><b>Оригинална окомплектовка</b><small>Подгответе опаковката, принадлежностите и наличните документи за покупката.</small></span></div><div><RotateCcw size={20} /><span><b>Срок за изпращане или предаване</b><small>При упражнено право на отказ следвайте публикувания срок след уведомяването на ЖОАН.</small></span></div><div><BadgeAlert size={20} /><span><b>Не изпращайте без уточнение</b><small>Първо се свържете с екипа, за да получите правилните указания за конкретния случай.</small></span></div></div></div></section>

    <section className="page-frame returns-help-panel"><div><p className="eyebrow">Нужна е помощ?</p><h2>Свържете се с ЖОАН за насоки по вашата заявка.</h2><p>Това е информационна страница. Тя не подава автоматично заявление за връщане и не замества потвърждението от екипа.</p></div><div className="returns-contact-actions"><a href={`tel:${store.phones[2].replace(/[^0-9+]/g, "")}`}><Phone size={18} /><span>Обадете се<b>{store.phones[2]}</b></span></a><a href={`mailto:${store.email}?subject=${encodeURIComponent("Запитване за връщане")}`}><Mail size={18} /><span>Изпратете имейл<b>{store.email}</b></span></a><Link href="/contact"><MapPin size={18} /><span>Посетете магазина<b>{store.address}</b></span></Link></div></section>
  </main></Layout>;
}
