import { Layout, PageMeta } from "@/components/Storefront";
import { useLanguage } from "@/contexts/LanguageContext";
import { FileText, ShieldCheck } from "lucide-react";

const sections = {
  bg: [
    { id: "general", title: "Общи условия и дефиниции", body: ["Настоящите общи условия уреждат отношенията между „ЖОАН“ ЕООД и лицата, които използват сайта и онлайн магазина на ЖОАН.", "В текста „ЖОАН“ и „Дружеството“ означават „ЖОАН“ ЕООД, ЕИК 118 516 694, собственик на строителен хипермаркет ЖОАН и онлайн магазина. „Сайт“, „Акаунт“, „Онлайн магазин“, „Ползвател“, „Купувач“, „Потребител“, „Лични данни“ и „Наложен платеж“ се употребяват със значенията, описани в настоящите условия."] },
    { id: "registration", title: "Регистрация и информация за стоките", body: ["Сайтът може да се разглежда без регистрация. Регистрацията е доброволна и безплатна за определени функционалности; при нея се прилагат изискванията на настоящите условия.", "Информацията за стоките, включително технически характеристики, гаранции и начин на употреба, е предоставена от производителя или вносителя. ЖОАН си запазва правата, предвидени в настоящите условия, при неточна, непълна или подвеждащо представена информация."] },
    { id: "prices", title: "Цени, поръчки и плащане", body: ["Публикуваните цени са валидни към момента на публикуването и могат да бъдат променяни съгласно настоящите условия. Потвърдените от ЖОАН поръчки следват условията, приложими към тях.", "Плащането чрез наложен платеж се извършва при условията, приложими към поръчката. Крайната сума по поръчката включва приложимите данъци и такси, а обработването и доставката се изчисляват според адреса и характеристиките на пратката. Онлайн каталогът не събира платежни данни."] },
    { id: "delivery", title: "Доставка, преглед и рекламации", body: ["Настоящите условия предвиждат доставка до адреси на територията на Република България. Посочени са срокове за обработване според часа на поръчката и работните или празничните дни, доколкото не противоречат на сроковете на куриера.", "При получаване купувачът следва да прегледа стоката и да уведоми доставящото лице при явни недостатъци, липси или липсващи документи. Рекламациите се разглеждат по приложимите правила за защита на потребителите и/или търговската гаранция."] },
    { id: "withdrawal", title: "Право на отказ и гаранция", body: ["Настоящите условия посочват законова гаранция за съответствие съгласно приложимото потребителско законодателство.", "При приложимост потребителят има право на отказ в 14-дневен срок от получаването на стоката. Условията описват изискванията за състоянието, окомплектовката и връщането на стоката. Вижте страницата „Връщане“ за практическите стъпки и се свържете с екипа преди изпращане."] },
    { id: "privacy", title: "Лични данни и бисквитки", body: ["Условията описват категориите данни, които могат да се обработват, целите на обработването, възможните получатели при изпълнение на договорни или законови задължения, мерките за защита и сроковете за съхранение.", "Можете да поискате информация, корекция, възражение, оттегляне на съгласие или изтриване по реда на публикуваната политика. Бисквитките могат да се управляват чрез настройките на браузъра, като ограничаването им може да засегне определени функции."] },
    { id: "updates", title: "Други условия и актуализации", body: ["ЖОАН може да актуализира информацията и условията според публикуваните правила. Промените действат занапред и не засягат вече потвърдени поръчки, освен ако приложимото право не предвижда друго.", "За неуредените въпроси се прилага действащото законодателство на Република България. Условията съдържат и реда за решаване на спорове."] },
  ],
  en: [
    { id: "general", title: "General terms and definitions", body: ["These terms govern the relationship between JOAN Ltd. and people using Joan’s website and online store.", "In these terms, Joan and the Company mean JOAN Ltd., UIC 118 516 694, owner of the Joan building hypermarket and online store. Terms such as Website, Account, Online Store, User, Buyer, Consumer, Personal Data and Cash on Delivery have the meanings stated in these terms."] },
    { id: "registration", title: "Registration and product information", body: ["The website can be browsed without registration. Registration is voluntary and free for certain functions, subject to these terms.", "Product information, including technical characteristics, warranties and use, is supplied by the manufacturer or importer. Joan retains the rights stated in these terms where information is inaccurate, incomplete or misleading."] },
    { id: "prices", title: "Prices, orders and payment", body: ["Published prices are valid at publication and may change under these terms. Orders confirmed by Joan follow the terms applicable to them.", "Cash-on-delivery payment is handled under the terms applicable to the order. The final order amount includes applicable taxes and charges, while processing and delivery are calculated according to the address and shipment characteristics. The online catalogue does not collect payment details."] },
    { id: "delivery", title: "Delivery, inspection and complaints", body: ["These terms provide for delivery to addresses in Bulgaria, with processing timeframes based on the time of ordering and working or holiday days, where not inconsistent with courier timeframes.", "On receipt, the buyer should inspect the goods and notify the delivering party of visible defects, missing items or missing documents. Complaints are handled under applicable consumer-protection rules and/or commercial warranty."] },
    { id: "withdrawal", title: "Withdrawal right and warranty", body: ["These terms state a statutory guarantee of conformity under applicable consumer law.", "Where applicable, the consumer has a 14-day withdrawal right from receiving the goods. The terms describe requirements for the condition, completeness and return of goods. See the Returns page for practical steps and contact the team before sending."] },
    { id: "privacy", title: "Personal data and cookies", body: ["The terms describe the categories of data that may be processed, the processing purposes, possible recipients for contractual or legal obligations, security measures and retention periods.", "You may request information, correction, objection, withdrawal of consent or deletion under the published policy. Cookies can be managed in browser settings, although restricting them may affect certain functions."] },
    { id: "updates", title: "Other terms and updates", body: ["Joan may update information and terms under the published rules. Changes apply prospectively and do not affect already confirmed orders unless applicable law provides otherwise.", "Bulgarian law applies to matters not settled. The terms also contain the dispute-resolution procedure."] },
  ],
} as const;

export default function Terms() {
  const { language } = useLanguage();
  const en = language === "en";
  const items = sections[language];
  return <Layout><PageMeta title={en ? "Terms of use" : "Условия за ползване"} description={en ? "Terms of use, delivery, returns, personal data and customer rights at Joan." : "Условия за ползване, доставка, връщане, лични данни и клиентски права на ЖОАН."} /><main className="terms-page terms-full-page"><section className="terms-hero"><div className="page-frame"><p className="eyebrow">{en ? "Legal information" : "Правна информация"}</p><h1>{en ? "Terms of use" : "Условия за ползване"}</h1><p>{en ? "Read Joan’s terms, customer rights and information about data processing." : "Запознайте се с условията на ЖОАН, клиентските права и обработването на данни."}</p></div></section><section className="page-frame terms-layout"><aside className="terms-index" aria-label={en ? "Contents" : "Съдържание"}><p className="eyebrow">{en ? "Contents" : "Съдържание"}</p>{items.map((section, index) => <a key={section.id} href={`#${section.id}`}>{String(index + 1).padStart(2, "0")} {section.title}</a>)}</aside><div className="terms-content"><div className="terms-notice"><ShieldCheck size={21} /><p>{en ? "This page presents Joan’s current customer terms and legal information. For a question about a specific order, please contact the team." : "Тази страница представя условията и правната информация за клиенти на ЖОАН. При въпрос за конкретна поръчка се свържете с екипа."}</p></div>{items.map((section, index) => <article id={section.id} key={section.id} className="terms-section"><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{section.title}</h2>{section.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></article>)}<div className="terms-final"><FileText size={22} /><div><h2>{en ? "Questions about the terms?" : "Въпроси за условията?"}</h2><p>{en ? "Contact the Joan team for information concerning a specific order, delivery or return." : "Свържете се с екипа на ЖОАН за информация относно конкретна поръчка, доставка или връщане."}</p></div></div></div></section></main></Layout>;
}
